version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the skill-share binary
    cmds:
      - go build -o bin/skill-share .
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - bin/skill-share

  install:
    desc: Install skill-share to GOPATH/bin
    cmds:
      - go install .
      - echo "Installed to {{.GOPATH}}/bin/skill-share"
    vars:
      GOPATH:
        sh: go env GOPATH

  clean:
    desc: Remove built binaries
    cmds:
      - rm -rf bin

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy
